name: publish

on:
  release:
    types: [published]

permissions:
  id-token: write  # Required for OIDC (publishing to NPM)
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm test
      - run: npm run build
      - run: npm publish

      - name: Docker Login
        run: echo ${{ secrets.SPECMATIC_DOCKER_HUB_TOKEN }} | docker login -u ${{ vars.SPECMATIC_DOCKER_HUB_USERNAME }} --password-stdin

      - name: Read version from package.json
        id: read_version
        run: |
          echo "Reading version from package.json..."
          version=$(jq -r '.version' package.json)
          echo "VERSION: $version"
          echo "VERSION=$version" >> "$GITHUB_OUTPUT"

      - name: Build Docker Image
        run: docker build --no-cache -t specmatic/specmatic-insights-github-build-reporter:${{ steps.read_version.outputs.VERSION }} .

      - name: Push Docker Image
        run: docker push specmatic/specmatic-insights-github-build-reporter:${{ steps.read_version.outputs.VERSION }}

      - name: Tag as latest
        run: docker tag specmatic/specmatic-insights-github-build-reporter:${{ steps.read_version.outputs.VERSION }} specmatic/specmatic-insights-github-build-reporter:latest && docker push specmatic/specmatic-insights-github-build-reporter:latest

    
